# Generated by Django 6.0.4 on 2026-04-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.CharField(choices=[('Educación básica', 'Educación básica'), ('Educación secundaria', 'Educación secundaria'), ('Bachillerato', 'Bachillerato'), ('Técnico', 'Técnico'), ('Profesional titulado', 'Profesional titulado'), ('Diplomado', 'Diplomado'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], default='Profesional', max_length=20),
        ),
    ]
