# Generated by Django 6.0.5 on 2026-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_fondo',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
