# Generated by Django 6.0.4 on 2026-04-28 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guardados',
            field=models.ManyToManyField(blank=True, related_name='post_guardados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='Category',
            field=models.CharField(choices=[('Educación básica', 'Educación básica'), ('Educación secundaria', 'Educación secundaria'), ('Bachillerato', 'Bachillerato'), ('Técnico', 'Técnico'), ('Profesional titulado', 'Profesional titulado'), ('Diplomado', 'Diplomado'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], default='Profesional titulado', max_length=50),
        ),
    ]
