# Generated by Django 6.0.4 on 2026-04-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_guardados_post_likes_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='guardados',
        ),
    ]
