# Generated by Django 6.0.4 on 2026-05-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_post_guardados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='Category',
            field=models.CharField(choices=[('Educación básica', 'Educación básica'), ('Educación secundaria', 'Educación secundaria'), ('Bachillerato', 'Bachillerato'), ('Técnico', 'Técnico'), ('Profesional titulado', 'Profesional titulado'), ('Diplomado', 'Diplomado'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], default='Profesional', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
