# Generated by Django 6.0.4 on 2026-05-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_foto_fondo'),
        ('app', '0008_alter_post_image_alter_profile_foto'),
    ]

    operations = [
    ]
